backend:
  name: github
  repo: rockysantiago/gatsby-netlify-i18n
  branch: master # Branch to update

media_folder: static/media
public_folder: media

collections:
  - name: pages
    label: Pages
    folder: pages
    create: true
    editor:
      preview: false
    fields:
      - name: title
        label: Title
      - name: 'home_en'
        label: Home in English
        widget: object
        fields:
          - name: heading
            label: Heading
      - name: 'home_zh'
        label: Home in Chinese
        widget: object
        fields:
          - name: heading
            label: Heading
